language: node_js
matrix:
  fast_finish: true
node_js:
- '8'
branches:
  except:
  - build
env:
  global:
  # LucsT GITHUB_TOKEN
  - secure: "YCWZe1x6D+L38VU+NElEIHMtoRgiqS90mLGaq5mIZBAoriUP8A4SpNMsFFUw027t4jcjBJsb9gXR71llIKk85UjxQ8didBZU8ovgkLKefXSeAInYH8iRPJGolmoAQb4LVTGHmRVBnI8sHusLM7wVaeHkkOYdX7une7RkZBPaGDMHro1Tez+03xfrewA8/Vp03n9zZ0qtBhPikX99/gehss4CrzBzalfwXfoS7NO+ed3JDWQ2a0U1S2sNq1AC43cgWhd4bMxKBgHqXjI1NtiMWKGuRgn4V7XM4S3uE8y8ZUruGyByLdol/i72NW/1ox+gcZIcWzGQDpEQR2s18CH10i6oDrLtzTGozLPxm2Ymteyl2Y2EIMa5+3Ctdil8sL/RuQKwTE1HbKPaazx3EOhwU2CddwZAI5azUZmPzEuftCdbjvZAp6kXzfn759VeutB97AAWk8KLTtfKTbFKmvMIjsLlpEbcQGrHV8m99uY2/SxuiZg1AXotijJCr2ErW62clOHAZwqle8wJBF9JgJ554VJaMy72cJBkA/GpBShQOl/0uDqAF7OASnyRbdKqqOrpuwRtDvgKsSfBKeTYh4qY6wEWTbfk5/DaD1aYkGi8YQsDdIBuhoNmIJYHi6H7Sc5196geJklCyl0v9W5vgT+rzYGSrjqKL07IEnG3QXMyiBM="
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn lint
  - yarn build
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-theoldreader
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-theoldreader
    skip-cleanup: true
    script: yarn deploy:prod
    on:
      branch: prod